import { isIncapacitated } from '../helpers/rolls.mjs';

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class HeroesGloryActor extends Actor {
  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...this.system.getRollData?.() ?? null };
  }

  /**
   * §5.9: "ОЗ ≤ 0 → недееспособен до конца боя." Fires on *any* update
   * that touches `system.health.value` — a manual GM edit on the sheet
   * today, or automated damage in the future — rather than being tied to
   * one specific code path, so it can't be bypassed by whichever way the
   * value happens to change.
   * @override
   */
  _onUpdate(changed, options, userId) {
    super._onUpdate(changed, options, userId);

    // Only the client that made this change drives the follow-up status
    // toggle, so it isn't attempted redundantly on every connected client.
    if (userId !== game.user.id) return;
    if (changed.system?.health?.value === undefined) return;
    if (!isIncapacitated(this.system.health.value)) return;

    this.toggleStatusEffect(CONFIG.HEROES_GLORY.statusEffects.incapacitated, { active: true });
  }

  /**
   * Convert the actor document to a plain object.
   *
   * The built in `toObject()` method will ignore derived data when using Data Models.
   * This additional method will instead use the spread operator to return a simplified
   * version of the data.
   *
   * @returns {object} Plain object either via deepClone or the spread operator.
   */
  toPlainObject() {
    const result = {...this};

    // Simplify system data.
    result.system = this.system.toPlainObject();

    // Add items.
    result.items = this.items?.size > 0 ? this.items.contents : [];

    // Add effects.
    result.effects = this.effects?.size > 0 ? this.effects.contents : [];

    return result;
  }

}
