import { isIncapacitated } from '../helpers/rolls.mjs';
import { subchoiceModifiersFor } from '../helpers/race-stats.mjs';
import { specializationModifiers, pickSpecialization } from '../helpers/specializations.mjs';
import { buildEffectChanges } from '../helpers/modifiers.mjs';
import { summonedData, dismissSummoned } from '../helpers/combat.mjs';
import { showHealthPopup } from '../helpers/health-popup.mjs';

/**
 * The flag namespace/key marking the ActiveEffect this system auto-manages
 * from a hero's `system.raceSubchoice` (rules.md §2.3, Элементаль/Минотавр)
 * — same convention as documents/item.mjs's own MODIFIER_EFFECT_FLAG for
 * an artifact's modifiers, distinguishing this auto-managed effect from
 * anything a GM adds by hand through Foundry's own effects UI.
 */
const RACE_SUBCHOICE_EFFECT_FLAG = ['heroes-glory', 'raceSubchoiceModifiers'];

/**
 * The flag of the specialization's in-memory effect (§4.3, Интеллект's +50
 * Mana — `specializationEffect`). Never stored: a stored effect with the
 * old flag `specializationModifiers` is what the world migration removes
 * (helpers/specialization-migration.mjs).
 */
const SPECIALIZATION_EFFECT_FLAG = ['heroes-glory', 'specializationEffect'];

/**
 * The specialization effect of each hero, cached per item and key. A
 * module-level map, not a private field: core prepares a document's data
 * inside its constructor, before a subclass's private members exist.
 * @type {WeakMap<Actor, {tag: string, effect: ActiveEffect}>}
 */
const specializationEffectCache = new WeakMap();

/**
 * A hero's specialization effect (§4.3, Интеллект's +50 Mana), built in
 * memory from its specialization item — `HeroesGloryActor#allApplicableEffects`.
 * @param {Actor} actor
 * @returns {ActiveEffect|null}
 */
function specializationEffect(actor) {
  if (actor.type !== 'hero' || !actor.items) return null;
  const items = actor.items.filter((i) => i.type === 'specialization')
    .map((i) => ({ id: i.id, sort: i.sort, key: i.system.key }));
  const { spec, itemId } = pickSpecialization(items);
  const modifiers = spec ? specializationModifiers(spec.type, spec.key) : [];
  if (!modifiers.length) return null;
  const tag = `${itemId}:${spec.key}`;
  const cached = specializationEffectCache.get(actor);
  if (cached?.tag === tag) return cached.effect;
  const effect = new CONFIG.ActiveEffect.documentClass({
    name: game.i18n?.localize('HEROES_GLORY.Hero.SpecializationEffectName') ?? spec.key,
    img: 'icons/svg/aura.svg',
    origin: actor.items.get(itemId)?.uuid ?? null,
    system: { changes: buildEffectChanges(modifiers) },
    flags: { [SPECIALIZATION_EFFECT_FLAG[0]]: { [SPECIALIZATION_EFFECT_FLAG[1]]: true } },
  }, { parent: actor });
  specializationEffectCache.set(actor, { tag, effect });
  return effect;
}

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class HeroesGloryActor extends Actor {
  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  /**
   * A hero is a player's character: its token is linked by default, so
   * damage, Mana, experience and the rest land on the hero's own sheet,
   * not on a token copy. An explicit `prototypeToken.actorLink` in the
   * creation data is kept.
   * @override
   */
  async _preCreate(data, options, user) {
    const allowed = await super._preCreate(data, options, user);
    if (allowed === false) return false;
    if (this.type === 'hero' && data.prototypeToken?.actorLink === undefined) {
      this.updateSource({ 'prototypeToken.actorLink': true });
    }
  }

  getRollData() {
    return { ...super.getRollData(), ...this.system.getRollData?.() ?? null };
  }

  /**
   * §5.9: "ОЗ ≤ 0 → недееспособен до конца боя." Fires on *any* update
   * that touches `system.health.value` — a manual GM edit on the sheet
   * today, or automated damage in the future — rather than being tied to
   * one specific code path, so it can't be bypassed by whichever way the
   * value happens to change.
   * @override
   */
  /**
   * Notes a drop in Health for _onUpdate — Слепота ends on any damage — and
   * the Health before it, for the number rising over the token.
   * @override
   */
  async _preUpdate(changed, options, user) {
    const next = changed.system?.health?.value;
    if (next !== undefined && next < (this.system.health?.value ?? next)) {
      options['heroes-glory'] = { ...options['heroes-glory'], healthDropped: true };
    }
    if (next !== undefined && this.system.health?.value !== undefined) {
      options['heroes-glory'] = { ...options['heroes-glory'], healthBefore: this.system.health.value };
    }
    return super._preUpdate(changed, options, user);
  }

  _onUpdate(changed, options, userId) {
    super._onUpdate(changed, options, userId);

    // «−N» / «+N» over the token, on every client that sees it; the colour
    // by its source (`damageKind` from the caller, health-popup.mjs).
    const before = options?.['heroes-glory']?.healthBefore;
    if (before !== undefined && changed.system?.health?.value !== undefined) {
      showHealthPopup(this, this.system.health.value - before, options['heroes-glory'].damageKind ?? null);
    }

    // Слепота (p. 59): «Заклинание отменяется, если цель получит урон» —
    // only a drop in Health (rules.md §11). The client that dealt it acts.
    if (userId === game.user.id && options?.['heroes-glory']?.healthDropped) {
      const ids = this.effects.filter((effect) => effect.getFlag('heroes-glory', 'spellEffect')?.skipsTurn).map((effect) => effect.id);
      if (ids.length) this.deleteEmbeddedDocuments('ActiveEffect', ids);
    }

    // Only the client that made this change drives the follow-up status
    // toggle, so it isn't attempted redundantly on every connected client.
    // `keepStatuses` — the caller sets the statuses itself (Воскрешение
    // ending: dead again, helpers/combat.mjs).
    // Group Д: a summoned elemental at 0 Здоровья doesn't lie down — «пока не
    // погибнет, а затем исчезает» (p. 61, rules.md §11). The active GM acts.
    // A clone: «получив любой урон, немедленно исчезает» (p. 58) — any drop in
    // Здоровье; a miss or 0 damage changes nothing (rules.md §11).
    const summoned = summonedData(this);
    if (summoned?.kind === 'clone') {
      if (options?.['heroes-glory']?.healthDropped) dismissSummoned(this.token, 'CloneVanished');
    } else if (summoned && changed.system?.health?.value !== undefined && isIncapacitated(this.system.health.value)) {
      dismissSummoned(this.token, 'SummonFell');
    } else if (userId === game.user.id && changed.system?.health?.value !== undefined
      && isIncapacitated(this.system.health.value) && !options?.['heroes-glory']?.keepStatuses) {
      this.toggleStatusEffect(CONFIG.HEROES_GLORY.statusEffects.incapacitated, { active: true });
    }

    // §2.3: keep the race-subchoice ActiveEffect (Элементаль/Минотавр
    // numeric bonus) in sync whenever race or the subchoice itself changes
    // — covers a race change away (subchoice cleared -> effect removed),
    // a race change into a subchoice race, and picking a different
    // subchoice for the same race. Same "only the driving client acts"
    // guard as above, and hero-only (`type` check) since creature actors
    // have neither field.
    if (userId === game.user.id && this.type === 'hero'
      && ('race' in (changed.system ?? {}) || 'raceSubchoice' in (changed.system ?? {}))) {
      this.#syncRaceSubchoiceEffect();
    }

  }

  /**
   * Always rebuilds the full effect data and calls `update()` rather than
   * diffing — same reasoning as documents/item.mjs's own
   * `#syncModifierEffect`: Foundry only writes an actual change if
   * something differs, so this stays simple without being wasteful.
   * `transfer` isn't set (unlike the item version) — this effect is
   * created directly on the actor, not on an owned item, so there's
   * nothing to transfer from.
   * @returns {Promise<void>}
   */
  async #syncRaceSubchoiceEffect() {
    const modifiers = subchoiceModifiersFor(this.system.race, this.system.raceSubchoice);
    const existing = this.effects.find((e) => e.getFlag(...RACE_SUBCHOICE_EFFECT_FLAG));

    if (modifiers.length === 0) {
      if (existing) await existing.delete();
      return;
    }

    const effectData = {
      name: game.i18n.localize('HEROES_GLORY.Hero.RaceSubchoiceEffectName'),
      icon: 'icons/svg/aura.svg',
      origin: this.uuid,
      system: { changes: buildEffectChanges(modifiers) },
      flags: { [RACE_SUBCHOICE_EFFECT_FLAG[0]]: { [RACE_SUBCHOICE_EFFECT_FLAG[1]]: true } },
    };

    if (existing) await existing.update(effectData);
    else await this.createEmbeddedDocuments('ActiveEffect', [effectData]);
  }

  /**
   * Core's list of effects to apply, plus the specialization's — an effect
   * that exists only in memory, rebuilt from the specialization item, never
   * stored (nothing to keep in sync, nothing for the GM to edit or delete).
   *
   * Why here and not in prepareDerivedData (rules.md §4.3): its change is
   * `mana.max` add 50 in the "final" phase, as the old stored effect's was,
   * and core applies all of one phase's changes sorted by priority —
   * multiply (10), add (20), downgrade, upgrade, override. An artifact may
   * multiply `mana.max` (its modifier modes allow it): Mana = derived × M +
   * 50 + the artifacts' adds. Added in prepareDerivedData the +50 would come
   * before the multiplier — (derived + 50) × M; added after the final phase
   * an override would no longer replace it. Here it takes its old place.
   * @override
   */
  *allApplicableEffects() {
    yield* super.allApplicableEffects();
    const effect = specializationEffect(this);
    if (effect) yield effect;
  }

  /**
   * Convert the actor document to a plain object.
   *
   * The built in `toObject()` method will ignore derived data when using Data Models.
   * This additional method will instead use the spread operator to return a simplified
   * version of the data.
   *
   * @returns {object} Plain object either via deepClone or the spread operator.
   */
  toPlainObject() {
    const result = {...this};

    // Simplify system data.
    result.system = this.system.toPlainObject();

    // Add items.
    result.items = this.items?.size > 0 ? this.items.contents : [];

    // Add effects.
    result.effects = this.effects?.size > 0 ? this.effects.contents : [];

    return result;
  }

}
